services:
  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093

      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:29092,CONTROLLER://:29093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  postgres:
    image: postgres:16
    container_name: parking_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: smart_parking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - parking_pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  spark:
    image: apache/spark:4.2.0-python3
    profiles: ["pipeline"]
    restart: unless-stopped
    user: "0:0"
    depends_on:
      - kafka
    working_dir: /opt/project
    volumes:
      - .:/opt/project
      - spark_checkpoints:/opt/checkpoints
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: parking-events
      KAFKA_STARTING_OFFSETS: earliest
      PARKING_STREAM_OUTPUT_ROOT: /opt/project/data/processed
      PARKING_CHECKPOINT_ROOT: /opt/checkpoints/rocksdb-v3
    entrypoint: ["/opt/spark/bin/spark-submit"]
    command:
      - --master
      - local[2]
      - --packages
      - org.apache.spark:spark-sql-kafka-0-10_2.13:4.2.0
      - --conf
      - spark.ui.enabled=false
      - --conf
      - spark.jars.ivy=/tmp/.ivy2
      - streaming/spark_streaming.py

volumes:
  parking_pgdata:
  spark_checkpoints:
